PygmentsCodeFences = true
PygmentsStyle = "monokai"
archetypeDir = "archetypes"
baseURL = "https://ffg-blog.netlify.app/"
buildDrafts = false
buildExpired = false
buildFuture = false
canonifyURLs = true
contentDir = "content"
copyright = "This work is licensed under a MIT License."
dataDir = "data"
disable404 = false
disableHugoGeneratorInject = false
disableRSS = false
disableSitemap = false
enableEmoji = true
enableGitInfo = false
enableMissingTranslationPlaceholders = false
enableRobotsTXT = true
languageCode = "en-us"
layoutDir = "layouts"
paginate = 10
publishDir = "public"
rssLimit = 10
theme = "timeline"
themesDir = "./themes"
title = "Timeline"
[author]
name = "timeline"
[blackfriday]
hrefTargetBlank = true
[languages.en]
copyright = ""
subtitle = "Timeline"
weight = 1
[languages.fr]
copyright = "<a href=\"https://github.com/s4n7h0/hugo-theme-timeline/blob/main/LICENSE\" target=\"_blank\" rel=\"noopener\">MIT</a>"
subtitle = "Timeline"
weight = 2
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
identifier = "timeline"
name = "Timeline"
url = "timeline/"
weight = 1
[params]
customCSS = ["css/custom.css"]
customJS = []
dateform = "Jan 2, 2006"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04 -0700"
dateformShort = "Jan 2"
defaultTheme = "dark"
description = "Timeline hugo template for your work experience, researches, achievement and more"
disableReadOtherPosts = false
enableSharingButtons = true
homeSubtitle = "timeline template for hugo"
images = [""]
justifyContent = false
keywords = "timeline hugo template"
themeColor = "#252627"
[params.favicon.color]
mask = "#252627"
msapplication = "#252627"
theme = "#252627"
[params.logo]
logoHomeLink = "/"
logoText = "$"
[[params.social]]
name = "twitter"
url = "#"
[[params.social]]
name = "instagram"
url = "#"
[[params.social]]
name = "facebook"
url = "#"
[[params.social]]
name = "linkedin"
url = "#"
[[params.social]]
name = "github"
url = "#"
[[params.social]]
name = "reddit"
url = "#"
[[params.social]]
name = "keybase"
url = "#"
[permalinks]
posts = "/posts/:year/:month/:title/"
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
